/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'arun.menon' at '3/13/16 11:05 AM' with Gradle 2.11
 *
 * @author arun.menon, @date 3/13/16 11:05 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
